# Generated by Django 4.1.2 on 2022-10-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='')),
                ('Description', models.TextField()),
            ],
        ),
    ]
